
title: Wirespec
tagline: '_Readable contracts and typesafe wires made easy_'
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Project's documentation.
# Custom vars
version:          0.0.2

github:
  repo:           https://github.com/Stef3st/wirespec

github_username:  Stef3st
git_repo:         wirespec
git_branch:       main

baseurl: ""
url: ""

defaults:
  - 
    scope:
      path: "README.md"
    values:
      permalink: "README.html"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
